version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - task -d ../index_fund build || exit 1
      - soroban contract build --package index_fund_factory
      - soroban contract optimize --wasm ../../target/wasm32v1-none/release/index_fund_factory.wasm --wasm-out ../../target/wasm32v1-none/release/index_fund_factory.wasm
      - cp ../../target/wasm32v1-none/release/index_fund_factory.wasm ../../wasm/index_fund_factory.wasm

  test:
    deps:
      - build
    cmds:
      - task -d ../index build || exit 1
      - cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
